version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: command to echo environments
          command: |
            echo hmy name is $first_name


workflows:
  test-env-variables:
    jobs:
      - build
