version: 2.1
jobs:
  print-hello:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - run: python --version
      - run: echo print-hello
  print-world:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - run: python --version
      - run: echo print-world

workflows:
  welcome:
    jobs:
      - print-hello
      - print-world
